### ISSUE TITLE
Need to add quick ratio and current ratio to chapter 6

### ISSUE THREAD

**Issue by sschilbe** [hannah-meneley/CE3963#5]
Two useful functions that could be added to chapter six are the Quick ratio and the Current ratio

**Comment by jmajcan** [comment]
Will do

**Comment by hannah-meneley** [comment]
Quick-Ratio is actually acid-test ratio 
Current-Ratio is actually the working capital ratio 
But I'll add comments to make this more clear for you @sschilbe

**Comment by sschilbe** [comment]
I fucked up 🙋
